kind: pipeline
type: docker
name: build
platform: 
  os: linux
  arch: arm

steps:
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
  - dotnet test

---

kind: pipeline
type: exec
name: deploy

depends_on:
  - build

platform: 
  os: linux
  arch: arm

steps:
- name: deploy docker image
  commands: 
    - docker build . -t gfunc -f WebService/Dockerfile