kind: pipeline
type: docker
name: build
platform: 
  os: linux
  arch: arm

steps:
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
  - dotnet test

---

kind: pipeline
type: exec
name: deploy

trigger: 
  event:
    - promote
  target:
    - production

depends_on:
  - build

platform: 
  os: linux
  arch: arm

steps:
- name: deploy docker image
  commands: 
    - [ "$(docker ps -a | grep gfunc)" ] && docker-compose -f /media/drive/docker/gfunc/docker-compose.yml down
    - docker build . -t gfunc -f WebService/Dockerfile
    - docker image prune -f
    - docker-compose -f /media/drive/docker/gfunc/docker-compose.yml up -d